Update tests.yaml

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -27,16 +27,18 @@ jobs:
 
       - name: Run tests and log results
         run: |
-          python -m unittest test_app.py > test_reports.txt
-          if [ $? -eq 0 ]; then
-            echo "Tests Passed" >> test_reports.txt
+          python -m unittest test_app.py | tee test_reports.txt
+          tests_completed=$(grep -c 'Ran' test_reports.txt)
+          if grep -q 'FAILED' test_reports.txt; then
+            echo "Tests completed: $tests_completed, Result: Failed" >> test_summary.txt
+            exit 1
           else
-            echo "Tests Failed" >> test_reports.txt
+            echo "Tests completed: $tests_completed, Result: Success" >> test_summary.txt
           fi
-          cat test_reports.txt
 
       - name: Archive test reports
         uses: actions/upload-artifact@v2
         with:
             name: test-reports
-            path: test_reports.txt
+            path: test_reports.txt test_summary.txt
+
